version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: anonifyneuro
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: